package com.cn.zooey.common.consts;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * @author Fengzl
 * @date 2024/4/28 09:31
 * @desc
 **/
@AllArgsConstructor
@Getter
public enum CountryLangEnum {

    AD("安道尔", "AND", "ca"),
    AE("阿拉伯联合酋长国", "ARE", "ar"),
    AF("阿富汗", "AFG", "ps"),
    AG("安提瓜和巴布达", "ATG", "en"),
    AI("安圭拉", "AIA", "en"),
    AL("阿尔巴尼亚", "ALB", "sq"),
    AM("亚美尼亚", "ARM", "hy"),
    AN("荷属安的列斯群岛", "ANT", "nl"),
    AO("安哥拉", "AGO", "pt"),
    AQ("南极洲", "ATA", "en"),
    AR("阿根廷", "ARG", "es"),
    AS("东萨摩亚", "ASM", "sm"),
    AT("奥地利", "AUT", "de"),
    AU("澳大利亚", "AUS", "en"),
    AW("阿鲁巴", "ABW", "nl"),
    AX("奥兰群岛", "ALA", "sv"),
    AZ("阿塞拜疆", "AZE", "az"),
    BA("波斯尼亚和黑山共和国", "BIH", "hr"),
    BB("巴巴多斯", "BRB", "en"),
    BD("孟加拉", "BGD", "bn"),
    BE("比利时", "BEL", "nl"),
    BF("布基纳法索", "BFA", "fr"),
    BG("保加利亚", "BGR", "bg"),
    BH("巴林", "BHR", "ar"),
    BI("布隆迪", "BDI", "fr"),
    BJ("贝宁", "BEN", "fr"),
    BL("圣巴泰勒米岛", "BLM", "fr"),
    BM("百慕大", "BMU", "en"),
    BN("文莱", "BRN", "ms"),
    BO("玻利维亚", "BOL", "es"),
    BQ("博奈尔岛, 圣尤斯特歇斯岛和萨巴岛", "BES", "nl"),
    BR("巴西", "BRA", "pt"),
    BS("巴哈马", "BHS", "en"),
    BT("不丹", "BTN", "en"),
    BV("布韦岛", "BVT", "no"),
    BW("博茨瓦纳", "BWA", "en"),
    BY("白俄罗斯", "BLR", "be"),
    BZ("伯里兹", "BLZ", "en"),
    CA("加拿大", "CAN", "en"),
    CC("科库斯群岛", "CCK", "en"),
    CD("刚果民主共和国", "COD", "fr"),
    CF("中非共和国", "CAF", "fr"),
    CG("刚果", "COG", "fr"),
    CH("瑞士", "CHE", "de"),
    CI("象牙海岸", "CIV", "fr"),
    CK("库克群岛", "COK", "en"),
    CL("智利", "CHL", "es"),
    CM("喀麦隆", "CMR", "fr"),
    CN("中国", "CHN", "zh"),
    CO("哥伦比亚", "COL", "es"),
    CR("哥斯达黎加", "CRI", "es"),
    CS("塞尔维亚及黑山", "SCG", "sr"),
    CU("古巴", "CUB", "es"),
    CV("佛得角", "CPV", "es"),
    CW("库拉索岛", "CUW", "nl"),
    CX("圣诞岛", "CXR", "en"),
    CY("塞浦路斯", "CYP", "el"),
    CZ("捷克共和国", "CZE", "cs"),
    DE("德国", "DEU", "de"),
    DJ("吉布提", "DJI", "fr"),
    DK("丹麦", "DNK", "da"),
    DM("多米尼加联邦", "DMA", "es"),
    DO("多米尼加共和国", "DOM", "fr"),
    DZ("阿尔及利亚", "DZA", "ar"),
    EC("厄瓜多尔", "ECU", "es"),
    EE("爱沙尼亚", "EST", "et"),
    EG("埃及", "EGY", "ar"),
    EH("西撒哈拉", "ESH", "ar"),
    ER("厄里特尼亚", "ERI", "am"),
    ES("西班牙", "ESP", "es"),
    ET("埃塞俄比亚", "ETH", "am"),
    FI("芬兰", "FIN", "fi"),
    FJ("斐济", "FJI", "en"),
    FK("福克兰群岛", "FLK", "en"),
    FM("密克罗尼西亚", "FSM", "en"),
    FO("法罗群岛", "FRO", "da"),
    FR("法国", "FRA", "fr"),
    GA("加蓬", "GAB", "fr"),
    GB("英国", "GBR", "en"),
    GD("格林纳达", "GRD", "en"),
    GE("格鲁吉亚", "GEO", "ka"),
    GF("法属圭亚那", "GUF", "fr"),
    GG("格恩西岛", "GGY", "en"),
    GH("加纳", "GHA", "en"),
    GI("直布罗陀", "GIB", "en"),
    GL("格陵兰", "GRL", "da"),
    GM("冈比亚", "GMB", "en"),
    GN("几内亚", "GIN", "fr"),
    GP("瓜德罗普岛", "GLP", "fr"),
    GQ("赤道几内亚", "GNQ", "es"),
    GR("希腊", "GRC", "el"),
    GS("南乔治亚岛和南桑德韦奇岛", "SGS", "en"),
    GT("危地马拉", "GTM", "es"),
    GU("关岛", "GUM", "en"),
    GW("几内亚比绍共和国", "GNB", "pt"),
    GY("圭亚那", "GUY", "es"),
    HK("香港", "HKG", "zh"),
    HM("赫德和麦克唐纳群岛", "HMD", "en"),
    HN("洪都拉斯", "HND", "es"),
    HR("克罗地亚", "HRV", "hr"),
    HT("海地", "HTI", "hr"),
    HU("匈牙利", "HUN", "hu"),
    ID("印度尼西亚", "IDN", "id"),
    IE("爱尔兰", "IRL", "ga"),
    IL("以色列", "ISR", "he"),
    IM("曼岛", "IMN", "en"),
    IN("印度", "IND", "hi"),
    IO("英属印度洋领地", "IOT", "en"),
    IQ("伊拉克", "IRQ", "ar"),
    IR("伊朗", "IRN", "fa"),
    IS("冰岛", "ISL", "is"),
    IT("意大利", "ITA", "it"),
    JE("泽西岛", "JEY", "en"),
    JM("牙买加", "JAM", "en"),
    JO("约旦", "JOR", "ar"),
    JP("日本", "JPN", "ja"),
    KE("肯尼亚", "KEN", "sw"),
    KG("吉尔吉克斯坦", "KGZ", "ru"),
    KH("柬埔寨", "KHM", "km"),
    KI("基里巴斯", "KIR", "en"),
    KM("科摩罗", "COM", "fr"),
    KN("圣基茨和尼维斯", "KNA", "en"),
    KP("朝鲜", "PRK", "ko"),
    KR("韩国", "KOR", "ko"),
    KW("科威特", "KWT", "ar"),
    KY("开曼群岛", "CYM", "en"),
    KZ("哈萨克斯坦", "KAZ", "kk"),
    LA("老挝", "LAO", "lo"),
    LB("黎巴嫩", "LBN", "ar"),
    LC("圣卢西亚", "LCA", "en"),
    LI("列支敦士登", "LIE", "de"),
    LK("斯里兰卡", "LKA", "si"),
    LR("利比里亚", "LBR", "en"),
    LS("莱索托", "LSO", "en"),
    LT("立陶宛", "LTU", "lt"),
    LU("卢森堡", "LUX", "lb"),
    LV("拉脱维亚", "LVA", "lv"),
    LY("利比亚", "LBY", "ar"),
    MA("摩洛哥", "MAR", "ar"),
    MC("摩纳哥", "MCO", "fr"),
    MD("摩尔多瓦", "MDA", "mo"),
    ME("黑山", "MNE", "en"),
    MF("圣马丁", "MAF", "nl"),
    MG("马达加斯加", "MDG", "mg"),
    MH("马绍尔群岛", "MHL", "en"),
    MK("马其顿王国", "MKD", "mk"),
    ML("马里", "MLI", "fr"),
    MM("缅甸", "MMR", "my"),
    MN("蒙古", "MNG", "mn"),
    MO("澳门特区", "MAC", "zh"),
    MP("美属北马里亚纳群岛", "MNP", "en"),
    MQ("马提尼克岛", "MTQ", "fr"),
    MR("毛里塔尼亚", "MRT", "ar"),
    MS("蒙特塞拉群岛", "MSR", "en"),
    MT("马耳他", "MLT", "mt"),
    MU("毛里求斯", "MUS", "en"),
    MV("马尔代夫", "MDV", "en"),
    MW("马拉维", "MWI", "en"),
    MX("墨西哥", "MEX", "es"),
    MY("马来西亚", "MYS", "ms"),
    MZ("莫桑比克", "MOZ", "pt"),
    NA("纳米比亚", "NAM", "en"),
    NC("新克里多尼亚群岛", "NCL", "fr"),
    NE("尼日尔", "NER", "fr"),
    NF("诺福克岛", "NFK", "en"),
    NG("尼日利亚", "NGA", "en"),
    NI("尼加拉瓜", "NIC", "es"),
    NL("荷兰", "NLD", "nl"),
    NO("挪威", "NOR", "no"),
    NP("尼泊尔", "NPL", "ne"),
    NR("瑙鲁", "NRU", "en"),
    NU("纽埃岛", "NIU", "en"),
    NZ("新西兰", "NZL", "en"),
    OM("阿曼", "OMN", "ar"),
    PA("巴拿马", "PAN", "es"),
    PE("秘鲁", "PER", "es"),
    PF("法属玻利尼西亚", "PYF", "fr"),
    PG("巴布亚新几内亚", "PNG", "en"),
    PH("菲律宾", "PHL", "tl"),
    PK("巴基斯坦", "PAK", "ur"),
    PL("波兰", "POL", "pl"),
    PM("圣皮埃尔和密克隆群岛", "SPM", "fr"),
    PN("皮特克恩岛", "PCN", "es"),
    PR("波多黎哥", "PRI", "es"),
    PS("巴勒斯坦", "PSE", "ar"),
    PT("葡萄牙", "PRT", "pt"),
    PW("帕劳", "PLW", "en"),
    PY("巴拉圭", "PRY", "es"),
    QA("卡塔尔", "QAT", "ar"),
    RE("留尼汪岛", "REU", "fr"),
    RO("罗马尼亚", "ROU", "ro"),
    RS("塞尔维亚", "SRB", "sr"),
    RU("俄罗斯", "RUS", "ru"),
    RW("卢旺达", "RWA", "rw"),
    SA("沙特阿拉伯", "SAU", "ar"),
    SB("所罗门群岛", "SLB", "en"),
    SC("塞舌尔群岛", "SYC", "en"),
    SD("苏丹", "SDN", "ar"),
    SE("瑞典", "SWE", "sv"),
    SG("新加坡", "SGP", "en"),
    SH("圣赫勒拿岛", "SHN", "en"),
    SI("斯洛文尼亚", "SVN", "sl"),
    SJ("斯瓦尔巴特和扬马延岛", "SJM", "no"),
    SK("斯洛伐克", "SVK", "sk"),
    SL("塞拉里昂", "SLE", "en"),
    SM("圣马力诺", "SMR", "it"),
    SN("塞内加尔", "SEN", "fr"),
    SO("索马里", "SOM", "so"),
    SR("苏里南", "SUR", "nl"),
    SS("南苏丹", "SSD", "en"),
    ST("圣多美和普林西比", "STP", "pt"),
    SV("萨尔瓦多", "SLV", "es"),
    SX("荷属圣马丁岛", "SXM", "nl"),
    SY("叙利亚", "SYR", "ar"),
    SZ("斯威士兰", "SWZ", "en"),
    TC("特克斯群岛和凯科斯群岛", "TCA", "en"),
    TD("乍得", "TCD", "fr"),
    TF("法属南特立尼达", "ATF", "fr"),
    TG("多哥", "TGO", "fr"),
    TH("泰国", "THA", "th"),
    TJ("塔吉克斯坦", "TJK", "tg"),
    TK("联合群岛", "TKL", "fr"),
    TL("东帝汶", "TLS", "pt"),
    TM("土库曼斯坦", "TKM", "tk"),
    TN("突尼斯", "TUN", "ar"),
    TO("汤加", "TON", "to"),
    TR("土耳其", "TUR", "tr"),
    TT("特立尼达和多巴哥", "TTO", "en"),
    TV("图瓦卢", "TUV", "en"),
    TW("台湾地区", "TWN", "zh"),
    TZ("坦桑尼亚", "TZA", "sw"),
    UA("乌克兰", "UKR", "uk"),
    UG("乌干达", "UGA", "sw"),
    UM("美属小奥特兰群岛", "UMI", "en"),
    US("美国", "USA", "en"),
    UY("乌拉圭", "URY", "es"),
    UZ("乌兹别克斯坦", "UZB", "uz"),
    VA("梵蒂冈", "VAT", "it"),
    VC("圣文森特和格林纳丁斯", "VCT", "en"),
    VE("委内瑞拉", "VEN", "es"),
    VG("英属维京群岛", "VGB", "en"),
    VI("美属维京群岛", "VIR", "en"),
    VN("越南", "VNM", "vi"),
    VU("瓦努阿图", "VUT", "bi"),
    WF("瓦利斯群岛和富图纳群岛", "WLF", "fr"),
    WS("东萨摩亚", "WSM", "sm"),
    YE("也门", "YEM", "ar"),
    YT("马约特岛", "MYT", "fr"),
    ZA("南非", "ZAF", "en"),
    ZM("赞比亚", "ZMB", "en"),
    ZW("津巴布韦", "ZWE", "en");


    /**
     * 名称
     */
    private final String name;
    /**
     * 三字母缩写
     */
    private final String code;
    /**
     * 语言
     */
    private final String lang;


    public static String transformCodeToLang(String code) {
        for (CountryLangEnum countryLangEnum : CountryLangEnum.values()) {
            if (countryLangEnum.getCode().equals(code)) {
                return countryLangEnum.getLang();
            }
        }
        return US.lang;
    }
}
